# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sheila Clark
email: sheila@sheilaclark.ca
description: >- # this means to ignore newlines until "baseurl:"
  I’ve had a passion for making things as far back as I can remember, discovering a particular passion for painting and sketching the prairie landscape, flowers, birds and nature.

Over the last few years I've been creating textile art pieces, sewing one of a kind ruffled aprons, bags, dresses, etc., perfecting my quilting skills, knitting and cross stitching.

My most recent ventures are as a result of our move to beautiful Vancouver Island.  I find all kinds of beautiful pieces of sea glass and pottery on the beaches, so I just have to create jewellery out of these gifts from the sea.
The sea and all her beautiful, wild, shores has lured me to paint and draw.

Thank you for visiting my site and I hope you enjoy looking at my gallery.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - .gitignore
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
